### ISSUE TITLE
Update to work on Latest Flutter

### ISSUE THREAD

**Issue by TekExplorer** [dahliaOS/xterm#1]
Hello! I've been using this instead of the official XTerm package, as it works better for my purposes.

Recently however, my project no longer builds due to this being outdated.

Any chance this gets updated?

**Comment by larsb24** [comment]
Hi, sorry to disappoint you there, but we actually aren't using this fork ourselves anymore, so it doesn't really make sense for us to maintain it anymore.

I would suggest you switch to the official package from pub.dev as the issues this fork was originally made for are fixed there now and it is updated frequently.

I didn't actually remember we still had that repo open. I'll archive it now.
